"""
query_bank_extension.py — 63 additional hand-labeled queries, bringing the
bank from 137 to 200.

These are deliberately weighted toward the exact failure patterns found in
benchmarking against real Qwen output:
  - infrastructure vs water/urban disambiguation (dams, canals, ports, power stations)
  - disaster vs forest/agriculture disambiguation (damage-framing vs plain description)
  - yes/no state questions that should be "vqa", not "grounding" or "change_vqa"
  - "what does X look like" / "describe" phrasing -> captioning, not vqa
  - target_object correctly null on every non-grounding entry here (this file
    doubles as a regression check for the interpreter.py fix that forces
    target_object=None when grounding isn't in task_sequence)

To merge into query_bank.py: import EXTENSION_QUERIES from this file and do
    QUERY_BANK.extend(EXTENSION_QUERIES)
at the bottom of query_bank.py, after the existing QUERY_BANK list is defined.
"""

from typing import Any, Dict, List

try:
    from .schema import Domain, InterpretedQuery, Sensor, Source, Task
except ImportError:
    from schema import Domain, InterpretedQuery, Sensor, Source, Task


EXTENSION_QUERIES: List[Dict[str, Any]] = [
    # =========================================================================
    # Infrastructure vs water/urban disambiguation [12 queries]
    # =========================================================================
    {
        "query": "Has the water level in the Bhakra dam reservoir dropped this summer?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Bhakra",
            date_or_time_reference="this summer",
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="Has the water level in the Bhakra dam reservoir dropped this summer?",
        ),
    },
    {
        "query": "Is the irrigation canal network near Indore carrying water currently?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Indore",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.88,
            source=Source.LLM,
            raw_query="Is the irrigation canal network near Indore carrying water currently?",
        ),
    },
    {
        "query": "What is the current water level of the Hirakud dam?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Hirakud",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.89,
            source=Source.LLM,
            raw_query="What is the current water level of the Hirakud dam?",
        ),
    },
    {
        "query": "Are the cooling water intake channels at the Kudankulam plant operational?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Kudankulam",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.87,
            source=Source.LLM,
            raw_query="Are the cooling water intake channels at the Kudankulam plant operational?",
        ),
    },
    {
        "query": "Highlight the port berths currently occupied at Kandla port.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Kandla",
            date_or_time_reference=None,
            target_object="the port berths",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="Highlight the port berths currently occupied at Kandla port.",
        ),
    },
    {
        "query": "Has the reservoir behind the Tehri dam expanded since last monsoon?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Tehri",
            date_or_time_reference="since last monsoon",
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="Has the reservoir behind the Tehri dam expanded since last monsoon?",
        ),
    },
    {
        "query": "Is there standing water pooling near this residential colony?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.85,
            source=Source.LLM,
            raw_query="Is there standing water pooling near this residential colony?",
        ),
    },
    {
        "query": "What is the turbidity level of the water in this lake?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.SAR,
            confidence=0.84,
            source=Source.LLM,
            raw_query="What is the turbidity level of the water in this lake?",
        ),
    },
    {
        "query": "Are the desalination plant intake pipes visible along this coastline?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.83,
            source=Source.LLM,
            raw_query="Are the desalination plant intake pipes visible along this coastline?",
        ),
    },
    {
        "query": "Locate the water treatment facility near Faridabad.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Faridabad",
            date_or_time_reference=None,
            target_object="the water treatment facility",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="Locate the water treatment facility near Faridabad.",
        ),
    },
    {
        "query": "Has the canal irrigation coverage expanded across this farmland since 2021?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location=None,
            date_or_time_reference="since 2021",
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.87,
            source=Source.LLM,
            raw_query="Has the canal irrigation coverage expanded across this farmland since 2021?",
        ),
    },
    {
        "query": "What is the color of the water near this power plant's discharge outlet?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.82,
            source=Source.LLM,
            raw_query="What is the color of the water near this power plant's discharge outlet?",
        ),
    },

    # =========================================================================
    # Disaster vs forest/agriculture disambiguation [12 queries]
    # =========================================================================
    {
        "query": "What is the density of tree cover remaining in this section of the Western Ghats?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.88,
            source=Source.LLM,
            raw_query="What is the density of tree cover remaining in this section of the Western Ghats?",
        ),
    },
    {
        "query": "How severe is the fire damage visible in this pine forest patch?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.89,
            source=Source.LLM,
            raw_query="How severe is the fire damage visible in this pine forest patch?",
        ),
    },
    {
        "query": "What crop varieties are visible in this agricultural belt near Ludhiana?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Ludhiana",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="What crop varieties are visible in this agricultural belt near Ludhiana?",
        ),
    },
    {
        "query": "Has the crop damage from the recent hailstorm affected this entire field?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference="recent",
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.86,
            source=Source.LLM,
            raw_query="Has the crop damage from the recent hailstorm affected this entire field?",
        ),
    },
    {
        "query": "Describe the mangrove vegetation density along this stretch of coastline.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.87,
            source=Source.LLM,
            raw_query="Describe the mangrove vegetation density along this stretch of coastline.",
        ),
    },
    {
        "query": "What is the extent of cyclone damage to the coastal tree line here?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.88,
            source=Source.LLM,
            raw_query="What is the extent of cyclone damage to the coastal tree line here?",
        ),
    },
    {
        "query": "Highlight the burn scar left by the wildfire in this hillside.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location=None,
            date_or_time_reference=None,
            target_object="the burn scar",
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="Highlight the burn scar left by the wildfire in this hillside.",
        ),
    },
    {
        "query": "What type of vegetation dominates this untouched forest reserve?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.88,
            source=Source.LLM,
            raw_query="What type of vegetation dominates this untouched forest reserve?",
        ),
    },
    {
        "query": "Is there visible drought stress across this wheat field?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.87,
            source=Source.LLM,
            raw_query="Is there visible drought stress across this wheat field?",
        ),
    },
    {
        "query": "How much crop area was destroyed by the flooding this season?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference="this season",
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.88,
            source=Source.LLM,
            raw_query="How much crop area was destroyed by the flooding this season?",
        ),
    },
    {
        "query": "Describe the canopy structure of this rainforest segment.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.87,
            source=Source.LLM,
            raw_query="Describe the canopy structure of this rainforest segment.",
        ),
    },
    {
        "query": "Has the drought severity in this agricultural belt worsened since April?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location=None,
            date_or_time_reference="since April",
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.88,
            source=Source.LLM,
            raw_query="Has the drought severity in this agricultural belt worsened since April?",
        ),
    },

    # =========================================================================
    # Yes/no state questions that should be "vqa", not "grounding" [13 queries]
    # =========================================================================
    {
        "query": "Are there any oil spills visible near this shipping lane?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.SAR,
            confidence=0.86,
            source=Source.LLM,
            raw_query="Are there any oil spills visible near this shipping lane?",
        ),
    },
    {
        "query": "Is there illegal encroachment visible along this forest boundary?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.85,
            source=Source.LLM,
            raw_query="Is there illegal encroachment visible along this forest boundary?",
        ),
    },
    {
        "query": "Are there any unauthorized structures near this riverbank?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.85,
            source=Source.LLM,
            raw_query="Are there any unauthorized structures near this riverbank?",
        ),
    },
    {
        "query": "Is the highway bridge near Patna still intact after the flooding?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Patna",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.88,
            source=Source.LLM,
            raw_query="Is the highway bridge near Patna still intact after the flooding?",
        ),
    },
    {
        "query": "Are there active mining operations visible in this quarry?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.86,
            source=Source.LLM,
            raw_query="Are there active mining operations visible in this quarry?",
        ),
    },
    {
        "query": "Is smoke visible over this forest region right now?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.86,
            source=Source.LLM,
            raw_query="Is smoke visible over this forest region right now?",
        ),
    },
    {
        "query": "Are there cracks visible on this dam wall?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.85,
            source=Source.LLM,
            raw_query="Are there cracks visible on this dam wall?",
        ),
    },
    {
        "query": "Is there sediment buildup at the mouth of this river delta?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.84,
            source=Source.LLM,
            raw_query="Is there sediment buildup at the mouth of this river delta?",
        ),
    },
    {
        "query": "Are any wind turbines visible in this offshore energy zone?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.85,
            source=Source.LLM,
            raw_query="Are any wind turbines visible in this offshore energy zone?",
        ),
    },
    {
        "query": "Is there active erosion along this coastal cliff?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.85,
            source=Source.LLM,
            raw_query="Is there active erosion along this coastal cliff?",
        ),
    },
    {
        "query": "Are any glaciers visibly retreating in this Himalayan valley?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.84,
            source=Source.LLM,
            raw_query="Are any glaciers visibly retreating in this Himalayan valley?",
        ),
    },
    {
        "query": "Are there livestock grazing visible in this pastureland?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.83,
            source=Source.LLM,
            raw_query="Are there livestock grazing visible in this pastureland?",
        ),
    },
    {
        "query": "Is there congestion visible at this highway toll plaza?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.83,
            source=Source.LLM,
            raw_query="Is there congestion visible at this highway toll plaza?",
        ),
    },

    # =========================================================================
    # "what does X look like" / "describe" -> captioning, not vqa [13 queries]
    # =========================================================================
    {
        "query": "What does this satellite image of the Thar desert boundary look like?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.OPTICAL,
            confidence=0.85,
            source=Source.LLM,
            raw_query="What does this satellite image of the Thar desert boundary look like?",
        ),
    },
    {
        "query": "Describe what you see in this uploaded coastal scene.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.OPTICAL,
            confidence=0.86,
            source=Source.LLM,
            raw_query="Describe what you see in this uploaded coastal scene.",
        ),
    },
    {
        "query": "What does the terrain around this mountain pass look like?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.OPTICAL,
            confidence=0.84,
            source=Source.LLM,
            raw_query="What does the terrain around this mountain pass look like?",
        ),
    },
    {
        "query": "Give me an overview of the industrial zone shown in this scene.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.86,
            source=Source.LLM,
            raw_query="Give me an overview of the industrial zone shown in this scene.",
        ),
    },
    {
        "query": "What does this radar image of the shipping channel look like?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.SAR,
            confidence=0.84,
            source=Source.LLM,
            raw_query="What does this radar image of the shipping channel look like?",
        ),
    },
    {
        "query": "Summarize the general layout of this hillside settlement.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.86,
            source=Source.LLM,
            raw_query="Summarize the general layout of this hillside settlement.",
        ),
    },
    {
        "query": "What does the delta region near Kolkata look like from this angle?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Kolkata",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.OPTICAL,
            confidence=0.85,
            source=Source.LLM,
            raw_query="What does the delta region near Kolkata look like from this angle?",
        ),
    },
    {
        "query": "Provide a general description of this agricultural valley.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.86,
            source=Source.LLM,
            raw_query="Provide a general description of this agricultural valley.",
        ),
    },
    {
        "query": "What does the reservoir shoreline near Nagpur look like this season?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Nagpur",
            date_or_time_reference="this season",
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.85,
            source=Source.LLM,
            raw_query="What does the reservoir shoreline near Nagpur look like this season?",
        ),
    },
    {
        "query": "Caption this scene of the tea plantations in Munnar.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Munnar",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.87,
            source=Source.LLM,
            raw_query="Caption this scene of the tea plantations in Munnar.",
        ),
    },
    {
        "query": "What does this cloud-covered scene over the Northeast look like?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.OPTICAL,
            confidence=0.82,
            source=Source.LLM,
            raw_query="What does this cloud-covered scene over the Northeast look like?",
        ),
    },
    {
        "query": "Describe the general condition of this quarry site.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.85,
            source=Source.LLM,
            raw_query="Describe the general condition of this quarry site.",
        ),
    },
    {
        "query": "What does the estuary near Bhitarkanika look like in this image?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Bhitarkanika",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.OPTICAL,
            confidence=0.84,
            source=Source.LLM,
            raw_query="What does the estuary near Bhitarkanika look like in this image?",
        ),
    },

    # =========================================================================
    # Chained tasks, upload-only, and short/terse queries [13 queries]
    # =========================================================================
    {
        "query": "Locate the reservoir and tell me if its water level changed since last year.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.CHANGE_VQA],
            location=None,
            date_or_time_reference="since last year",
            target_object="the reservoir",
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.84,
            source=Source.LLM,
            raw_query="Locate the reservoir and tell me if its water level changed since last year.",
        ),
    },
    {
        "query": "Highlight the deforested patch and describe how large it is.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object="the deforested patch",
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.83,
            source=Source.LLM,
            raw_query="Highlight the deforested patch and describe how large it is.",
        ),
    },
    {
        "query": "Fuse SAR and optical data for this scene and locate the flooded roads.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS, Task.GROUNDING],
            location=None,
            date_or_time_reference=None,
            target_object="the flooded roads",
            domain=Domain.DISASTER,
            sensor=Sensor.BOTH,
            confidence=0.86,
            source=Source.LLM,
            raw_query="Fuse SAR and optical data for this scene and locate the flooded roads.",
        ),
    },
    {
        "query": "what changed",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.UNSPECIFIED,
            confidence=0.35,
            source=Source.LLM,
            raw_query="what changed",
        ),
    },
    {
        "query": "highlight this",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.UNSPECIFIED,
            confidence=0.30,
            source=Source.LLM,
            raw_query="highlight this",
        ),
    },
    {
        "query": "fuse the sensors",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.BOTH,
            confidence=0.35,
            source=Source.LLM,
            raw_query="fuse the sensors",
        ),
    },
    {
        "query": "describe it",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.UNSPECIFIED,
            confidence=0.30,
            source=Source.LLM,
            raw_query="describe it",
        ),
    },
    {
        "query": "any damage here",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.UNSPECIFIED,
            confidence=0.35,
            source=Source.LLM,
            raw_query="any damage here",
        ),
    },
    {
        "query": "Locate the industrial rooftops and compare solar panel coverage to last year.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.CHANGE_VQA],
            location=None,
            date_or_time_reference="last year",
            target_object="the industrial rooftops",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.85,
            source=Source.LLM,
            raw_query="Locate the industrial rooftops and compare solar panel coverage to last year.",
        ),
    },
    {
        "query": "Combine radar and optical layers and describe the terrain here.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS, Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.BOTH,
            confidence=0.85,
            source=Source.LLM,
            raw_query="Combine radar and optical layers and describe the terrain here.",
        ),
    },
    {
        "query": "Pinpoint the airstrip and tell me if it's operational currently.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object="the airstrip",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.83,
            source=Source.LLM,
            raw_query="Pinpoint the airstrip and tell me if it's operational currently.",
        ),
    },
    {
        "query": "Mark the crop field boundary and estimate the harvest readiness.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object="the crop field boundary",
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.84,
            source=Source.LLM,
            raw_query="Mark the crop field boundary and estimate the harvest readiness.",
        ),
    },
    {
        "query": "Segment the shoreline and check if erosion increased since 2022.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.CHANGE_VQA],
            location=None,
            date_or_time_reference="since 2022",
            target_object="the shoreline",
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.84,
            source=Source.LLM,
            raw_query="Segment the shoreline and check if erosion increased since 2022.",
        ),
    },
]
