"""
query_bank.py — Curated ground-truth test bank for SatQuery AI.

Contains ~130+ hand-labeled remote-sensing queries spanning all 5 task types
(vqa, captioning, grounding, change_vqa, fusion_analysis), chained tasks,
upload-only queries (no location), all 7 domains, and multi-sensor modalities.
Used by test_interpreter.py and for LLM few-shot prompt construction.
"""

from typing import Any, Dict, List, Optional

try:
    from .schema import Domain, InterpretedQuery, Sensor, Source, Task
except ImportError:
    from schema import Domain, InterpretedQuery, Sensor, Source, Task


# ---------------------------------------------------------------------------
# Hand-Labeled Query Bank
# ---------------------------------------------------------------------------

QUERY_BANK: List[Dict[str, Any]] = [
    # =========================================================================
    # 1. Single-Task: VQA (Visual Question Answering) [25 queries]
    # =========================================================================
    {
        "query": "What does the land cover look like around Chennai?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Chennai",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.92,
            source=Source.LLM,
            raw_query="What does the land cover look like around Chennai?",
        ),
    },
    {
        "query": "How many cargo ships are docked at the port of Visakhapatnam?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Visakhapatnam",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="How many cargo ships are docked at the port of Visakhapatnam?",
        ),
    },
    {
        "query": "Is there active standing water in the agricultural fields near Cuttack?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Cuttack",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="Is there active standing water in the agricultural fields near Cuttack?",
        ),
    },
    {
        "query": "What type of crop is predominantly grown in this region of Punjab?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Punjab",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="What type of crop is predominantly grown in this region of Punjab?",
        ),
    },
    {
        "query": "Are there any newly constructed bridges across the Brahmaputra river?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Brahmaputra",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Are there any newly constructed bridges across the Brahmaputra river?",
        ),
    },
    {
        "query": "Estimate the percentage of dense forest canopy in the Western Ghats section shown.",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Western Ghats",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="Estimate the percentage of dense forest canopy in the Western Ghats section shown.",
        ),
    },
    {
        "query": "Is the airport runway in Leh clear of snow in this optical image?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Leh",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Is the airport runway in Leh clear of snow in this optical image?",
        ),
    },
    {
        "query": "What is the primary cause of discoloration in the Dal Lake waters?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Dal Lake",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.88,
            source=Source.LLM,
            raw_query="What is the primary cause of discoloration in the Dal Lake waters?",
        ),
    },
    {
        "query": "How many high-rise buildings are visible in this downtown Mumbai sector?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Mumbai",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="How many high-rise buildings are visible in this downtown Mumbai sector?",
        ),
    },
    {
        "query": "Are the irrigation canals around Godavari basin currently carrying water?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Godavari",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.89,
            source=Source.LLM,
            raw_query="Are the irrigation canals around Godavari basin currently carrying water?",
        ),
    },
    {
        "query": "What is the density of solar panels installed in this solar farm near Jodhpur?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Jodhpur",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.92,
            source=Source.LLM,
            raw_query="What is the density of solar panels installed in this solar farm near Jodhpur?",
        ),
    },
    {
        "query": "What is the extent of burn scar severity in the Nilgiris forest reserve?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Nilgiris",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="What is the extent of burn scar severity in the Nilgiris forest reserve?",
        ),
    },
    {
        "query": "Do you observe any industrial oil storage tanks near Kochi port?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Kochi",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="Do you observe any industrial oil storage tanks near Kochi port?",
        ),
    },
    {
        "query": "What proportion of this image is covered by urban residential zones?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="What proportion of this image is covered by urban residential zones?",
        ),
    },
    {
        "query": "Are there signs of crop water stress in this multispectral agricultural tile?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.88,
            source=Source.LLM,
            raw_query="Are there signs of crop water stress in this multispectral agricultural tile?",
        ),
    },
    {
        "query": "Count the number of aircraft parked on the aprons at Bengaluru airport.",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Bengaluru",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Count the number of aircraft parked on the aprons at Bengaluru airport.",
        ),
    },
    {
        "query": "Is the reservoir water level near Kota dam at full capacity?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Kota",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="Is the reservoir water level near Kota dam at full capacity?",
        ),
    },
    {
        "query": "What type of vegetation dominates the Sundarbans coastal boundary?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Sundarbans",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="What type of vegetation dominates the Sundarbans coastal boundary?",
        ),
    },
    {
        "query": "Assess whether the highway bypass around Varanasi is open for traffic.",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Varanasi",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.89,
            source=Source.LLM,
            raw_query="Assess whether the highway bypass around Varanasi is open for traffic.",
        ),
    },
    {
        "query": "Are there any landslides blocking the mountain passes in Uttarakhand?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Uttarakhand",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Are there any landslides blocking the mountain passes in Uttarakhand?",
        ),
    },
    {
        "query": "Is there cloud cover obstructing the view over Guwahati?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Guwahati",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="Is there cloud cover obstructing the view over Guwahati?",
        ),
    },
    {
        "query": "What is the dominant soil color in this arid tile from Thar Desert?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Thar Desert",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.87,
            source=Source.LLM,
            raw_query="What is the dominant soil color in this arid tile from Thar Desert?",
        ),
    },
    {
        "query": "What is the estimated height category of the buildings in this district?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.86,
            source=Source.LLM,
            raw_query="What is the estimated height category of the buildings in this district?",
        ),
    },
    {
        "query": "Can you verify if the thermal power station in Surat is operational?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location="Surat",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="Can you verify if the thermal power station in Surat is operational?",
        ),
    },
    {
        "query": "Which sector in this uploaded scene contains commercial establishments?",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.89,
            source=Source.LLM,
            raw_query="Which sector in this uploaded scene contains commercial establishments?",
        ),
    },

    # =========================================================================
    # 2. Single-Task: Captioning [25 queries]
    # =========================================================================
    {
        "query": "Describe the scene captured over the coastal wetlands of Kerala.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Kerala",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Describe the scene captured over the coastal wetlands of Kerala.",
        ),
    },
    {
        "query": "Provide a detailed caption for this urban satellite view of Delhi.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Delhi",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Provide a detailed caption for this urban satellite view of Delhi.",
        ),
    },
    {
        "query": "What does this image of the Rann of Kutch look like?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Rann Of Kutch",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.OPTICAL,
            confidence=0.92,
            source=Source.LLM,
            raw_query="What does this image of the Rann of Kutch look like?",
        ),
    },
    {
        "query": "Summarize the major geographical and infrastructural features shown in this frame.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="Summarize the major geographical and infrastructural features shown in this frame.",
        ),
    },
    {
        "query": "Generate a concise overview of the agricultural landscape in this image.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="Generate a concise overview of the agricultural landscape in this image.",
        ),
    },
    {
        "query": "Describe the flood damage visible in this post-cyclone scene around Bhubaneswar.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Bhubaneswar",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Describe the flood damage visible in this post-cyclone scene around Bhubaneswar.",
        ),
    },
    {
        "query": "Provide a descriptive summary of the forest density and canopy structure in Assam.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Assam",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Provide a descriptive summary of the forest density and canopy structure in Assam.",
        ),
    },
    {
        "query": "What is shown in this satellite imagery of the Mumbai port trust area?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Mumbai",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.92,
            source=Source.LLM,
            raw_query="What is shown in this satellite imagery of the Mumbai port trust area?",
        ),
    },
    {
        "query": "Give me a detailed description of the river meanders along the Ganga basin.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Ganga Basin",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Give me a detailed description of the river meanders along the Ganga basin.",
        ),
    },
    {
        "query": "Describe the spatial layout of the industrial corridor in Hyderabad.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Hyderabad",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.92,
            source=Source.LLM,
            raw_query="Describe the spatial layout of the industrial corridor in Hyderabad.",
        ),
    },
    {
        "query": "Provide a summary of the wildfire destruction in the pine forests of Shimla.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Shimla",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Provide a summary of the wildfire destruction in the pine forests of Shimla.",
        ),
    },
    {
        "query": "Caption this remote sensing image showing the Chilika Lake brackish lagoon.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Chilika Lake",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.96,
            source=Source.LLM,
            raw_query="Caption this remote sensing image showing the Chilika Lake brackish lagoon.",
        ),
    },
    {
        "query": "Describe the rural settlement patterns in this uploaded patch.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.88,
            source=Source.LLM,
            raw_query="Describe the rural settlement patterns in this uploaded patch.",
        ),
    },
    {
        "query": "What is visible in this SAR backscatter image of the mountain ridge?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.SAR,
            confidence=0.91,
            source=Source.LLM,
            raw_query="What is visible in this SAR backscatter image of the mountain ridge?",
        ),
    },
    {
        "query": "Generate a caption describing the dry riverbed and surrounding sandbars in Gujarat.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Gujarat",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Generate a caption describing the dry riverbed and surrounding sandbars in Gujarat.",
        ),
    },
    {
        "query": "Describe the dense mangrove vegetation in the Andaman islands.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Andaman",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Describe the dense mangrove vegetation in the Andaman islands.",
        ),
    },
    {
        "query": "Provide an overview of the railway junction and marshalling yard in Nagpur.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Nagpur",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Provide an overview of the railway junction and marshalling yard in Nagpur.",
        ),
    },
    {
        "query": "Tell me what you see in this satellite image of the Jaipur urban sprawl.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Jaipur",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.92,
            source=Source.LLM,
            raw_query="Tell me what you see in this satellite image of the Jaipur urban sprawl.",
        ),
    },
    {
        "query": "Summarize the visual features of the landslide impact zone in Wayanad Kerala.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Wayanad",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Summarize the visual features of the landslide impact zone in Wayanad Kerala.",
        ),
    },
    {
        "query": "Give me a high-level summary of the agricultural harvesting activity shown.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.89,
            source=Source.LLM,
            raw_query="Give me a high-level summary of the agricultural harvesting activity shown.",
        ),
    },
    {
        "query": "Describe the shoreline erosion visible along the Puducherry coastline.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Puducherry",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="Describe the shoreline erosion visible along the Puducherry coastline.",
        ),
    },
    {
        "query": "What does this high-resolution optical image of an oil refinery look like?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="What does this high-resolution optical image of an oil refinery look like?",
        ),
    },
    {
        "query": "Provide a caption for the glacial lake expansion in Ladakh Himalayas.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location="Ladakh",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Provide a caption for the glacial lake expansion in Ladakh Himalayas.",
        ),
    },
    {
        "query": "Describe the layout of informal housing settlements in this uploaded quadrant.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.88,
            source=Source.LLM,
            raw_query="Describe the layout of informal housing settlements in this uploaded quadrant.",
        ),
    },
    {
        "query": "Generate a descriptive caption for this radar backscatter image of an airport.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.SAR,
            confidence=0.92,
            source=Source.LLM,
            raw_query="Generate a descriptive caption for this radar backscatter image of an airport.",
        ),
    },

    # =========================================================================
    # 3. Single-Task: Grounding (Visual Localization) [25 queries]
    # =========================================================================
    {
        "query": "Highlight the water body located in central Bengaluru.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Bengaluru",
            date_or_time_reference=None,
            target_object="the water body",
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Highlight the water body located in central Bengaluru.",
        ),
    },
    {
        "query": "Show me where the flooded areas are in Patna.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Patna",
            date_or_time_reference=None,
            target_object="the flooded areas",
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.96,
            source=Source.LLM,
            raw_query="Show me where the flooded areas are in Patna.",
        ),
    },
    {
        "query": "Where is the main airport runway in Kochi?",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Kochi",
            date_or_time_reference=None,
            target_object="the runway",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Where is the main airport runway in Kochi?",
        ),
    },
    {
        "query": "Locate the agricultural fields with healthy crop vigor in this scene.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location=None,
            date_or_time_reference=None,
            target_object="the agricultural fields",
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="Locate the agricultural fields with healthy crop vigor in this scene.",
        ),
    },
    {
        "query": "Pinpoint all the oil storage tanks near the Chennai harbor.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Chennai",
            date_or_time_reference=None,
            target_object="the oil tanks",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Pinpoint all the oil storage tanks near the Chennai harbor.",
        ),
    },
    {
        "query": "Outline the dense forest patches remaining in the Nilgiris.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Nilgiris",
            date_or_time_reference=None,
            target_object="the forest cover",
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Outline the dense forest patches remaining in the Nilgiris.",
        ),
    },
    {
        "query": "Demarcate the built-up area boundary for Ahmedabad.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Ahmedabad",
            date_or_time_reference=None,
            target_object="the built-up area",
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Demarcate the built-up area boundary for Ahmedabad.",
        ),
    },
    {
        "query": "Box all maritime cargo vessels detected in the SAR image off Mumbai coast.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Mumbai",
            date_or_time_reference=None,
            target_object="the ships",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.SAR,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Box all maritime cargo vessels detected in the SAR image off Mumbai coast.",
        ),
    },
    {
        "query": "Find all submerged roads across the flooded districts of Assam.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Assam",
            date_or_time_reference=None,
            target_object="the submerged roads",
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.96,
            source=Source.LLM,
            raw_query="Find all submerged roads across the flooded districts of Assam.",
        ),
    },
    {
        "query": "Highlight the solar panels installed on building rooftops in Surat.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Surat",
            date_or_time_reference=None,
            target_object="the solar panels",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.92,
            source=Source.LLM,
            raw_query="Highlight the solar panels installed on building rooftops in Surat.",
        ),
    },
    {
        "query": "Where are the deforested patches located in this tropical rainforest segment?",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location=None,
            date_or_time_reference=None,
            target_object="the deforestation patches",
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Where are the deforested patches located in this tropical rainforest segment?",
        ),
    },
    {
        "query": "Segment the water reservoir boundary near Pune.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Pune",
            date_or_time_reference=None,
            target_object="the water reservoir",
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Segment the water reservoir boundary near Pune.",
        ),
    },
    {
        "query": "Identify the bounding box for the railway bridge over Godavari river.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Godavari",
            date_or_time_reference=None,
            target_object="the bridge",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Identify the bounding box for the railway bridge over Godavari river.",
        ),
    },
    {
        "query": "Show me where the landslide debris has accumulated along the slope.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location=None,
            date_or_time_reference=None,
            target_object="the landslide debris",
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Show me where the landslide debris has accumulated along the slope.",
        ),
    },
    {
        "query": "Point out all paddy fields under active irrigation in Haryana.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Haryana",
            date_or_time_reference=None,
            target_object="the paddy fields",
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.92,
            source=Source.LLM,
            raw_query="Point out all paddy fields under active irrigation in Haryana.",
        ),
    },
    {
        "query": "Highlight all commercial high-rise buildings in Gurgaon.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Gurgaon",
            date_or_time_reference=None,
            target_object="the buildings",
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Highlight all commercial high-rise buildings in Gurgaon.",
        ),
    },
    {
        "query": "Where is the dry lakebed in this arid tile?",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location=None,
            date_or_time_reference=None,
            target_object="the lakebed",
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="Where is the dry lakebed in this arid tile?",
        ),
    },
    {
        "query": "Locate the primary runway in this radar image of the airbase.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location=None,
            date_or_time_reference=None,
            target_object="the runway",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.SAR,
            confidence=0.92,
            source=Source.LLM,
            raw_query="Locate the primary runway in this radar image of the airbase.",
        ),
    },
    {
        "query": "Find the burn scar extent left by the forest fire in Uttarakhand.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Uttarakhand",
            date_or_time_reference=None,
            target_object="the burn scar",
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Find the burn scar extent left by the forest fire in Uttarakhand.",
        ),
    },
    {
        "query": "Mark the industrial warehouses along the highway near Lucknow.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Lucknow",
            date_or_time_reference=None,
            target_object="the warehouses",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Mark the industrial warehouses along the highway near Lucknow.",
        ),
    },
    {
        "query": "Highlight the mangrove forest zone along the Sundarbans shoreline.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Sundarbans",
            date_or_time_reference=None,
            target_object="the mangrove forest",
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.96,
            source=Source.LLM,
            raw_query="Highlight the mangrove forest zone along the Sundarbans shoreline.",
        ),
    },
    {
        "query": "Show me where the major highway interchange is in Noida.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Noida",
            date_or_time_reference=None,
            target_object="the highway interchange",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Show me where the major highway interchange is in Noida.",
        ),
    },
    {
        "query": "Locate all standing water pools in this urban area after rainfall.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location=None,
            date_or_time_reference=None,
            target_object="the standing water",
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="Locate all standing water pools in this urban area after rainfall.",
        ),
    },
    {
        "query": "Pinpoint the damaged bridge pier in this post-flood optical scene.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location=None,
            date_or_time_reference=None,
            target_object="the damaged bridge",
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Pinpoint the damaged bridge pier in this post-flood optical scene.",
        ),
    },
    {
        "query": "Where are the informal settlement clusters in this aerial scene?",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location=None,
            date_or_time_reference=None,
            target_object="the informal settlements",
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="Where are the informal settlement clusters in this aerial scene?",
        ),
    },

    # =========================================================================
    # 4. Single-Task: Change VQA (Temporal Comparison) [25 queries]
    # =========================================================================
    {
        "query": "How has the urban built-up area of Hyderabad changed between 2020 and 2024?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Hyderabad",
            date_or_time_reference="between 2020 and 2024",
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.96,
            source=Source.LLM,
            raw_query="How has the urban built-up area of Hyderabad changed between 2020 and 2024?",
        ),
    },
    {
        "query": "Compare the forest cover in Wayanad before and after the 2024 landslide.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Wayanad",
            date_or_time_reference="before and after the 2024 landslide",
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Compare the forest cover in Wayanad before and after the 2024 landslide.",
        ),
    },
    {
        "query": "What is the change in water surface area of Sambhar Lake before and after monsoon?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Sambhar Lake",
            date_or_time_reference="before and after monsoon",
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="What is the change in water surface area of Sambhar Lake before and after monsoon?",
        ),
    },
    {
        "query": "Evaluate the expansion of agricultural fields in Madhya Pradesh over the past decade.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Madhya Pradesh",
            date_or_time_reference="over the past decade",
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.92,
            source=Source.LLM,
            raw_query="Evaluate the expansion of agricultural fields in Madhya Pradesh over the past decade.",
        ),
    },
    {
        "query": "Did the mangrove density in Sundarbans decrease following the 2023 cyclone?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Sundarbans",
            date_or_time_reference="2023",
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Did the mangrove density in Sundarbans decrease following the 2023 cyclone?",
        ),
    },
    {
        "query": "Compare the pre-monsoon vs post-monsoon reservoir levels for Kota dam in 2023.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Kota",
            date_or_time_reference="pre-monsoon vs post-monsoon",
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Compare the pre-monsoon vs post-monsoon reservoir levels for Kota dam in 2023.",
        ),
    },
    {
        "query": "How much has the deforestation rate increased in the Amazon basin between 2021 and 2023?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Amazon",
            date_or_time_reference="between 2021 and 2023",
            target_object=None,
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="How much has the deforestation rate increased in the Amazon basin between 2021 and 2023?",
        ),
    },
    {
        "query": "Track the growth of highway infrastructure around Bengaluru from 2019 to 2024.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Bengaluru",
            date_or_time_reference="from 2019 to 2024",
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Track the growth of highway infrastructure around Bengaluru from 2019 to 2024.",
        ),
    },
    {
        "query": "Has the flood extent in Cuttack receded compared to last week?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Cuttack",
            date_or_time_reference="last week",
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="Has the flood extent in Cuttack receded compared to last week?",
        ),
    },
    {
        "query": "What is the difference in crop canopy health between Kharif season 2022 and 2023 in Punjab?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Punjab",
            date_or_time_reference="Kharif season 2022 and 2023",
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="What is the difference in crop canopy health between Kharif season 2022 and 2023 in Punjab?",
        ),
    },
    {
        "query": "Analyze urban sprawl in Pune 2020 vs 2024.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Pune",
            date_or_time_reference="2020 vs 2024",
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.96,
            source=Source.LLM,
            raw_query="Analyze urban sprawl in Pune 2020 vs 2024.",
        ),
    },
    {
        "query": "How did the river course of Brahmaputra change after the summer floods?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Brahmaputra",
            date_or_time_reference="after the summer floods",
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="How did the river course of Brahmaputra change after the summer floods?",
        ),
    },
    {
        "query": "Compare industrial expansion in Surat between 2021 and 2024.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Surat",
            date_or_time_reference="between 2021 and 2024",
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Compare industrial expansion in Surat between 2021 and 2024.",
        ),
    },
    {
        "query": "Assess the loss of forest greenery in the Nilgiris over the past 5 years.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Nilgiris",
            date_or_time_reference="over the past 5 years",
            target_object=None,
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Assess the loss of forest greenery in the Nilgiris over the past 5 years.",
        ),
    },
    {
        "query": "Did the coastal shoreline of Visakhapatnam change significantly over the last decade?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Visakhapatnam",
            date_or_time_reference="over the last decade",
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Did the coastal shoreline of Visakhapatnam change significantly over the last decade?",
        ),
    },
    {
        "query": "Compare the solar panel installation area in this region 2022 vs 2024.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location=None,
            date_or_time_reference="2022 vs 2024",
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Compare the solar panel installation area in this region 2022 vs 2024.",
        ),
    },
    {
        "query": "What structural damage occurred to the bridge before and after the flood?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location=None,
            date_or_time_reference="before and after the flood",
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="What structural damage occurred to the bridge before and after the flood?",
        ),
    },
    {
        "query": "How has vegetation index changed across this crop field over the past month?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location=None,
            date_or_time_reference="over the past month",
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="How has vegetation index changed across this crop field over the past month?",
        ),
    },
    {
        "query": "Compare the SAR radar backscatter intensities between May and August 2023.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location=None,
            date_or_time_reference="between May and August 2023",
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.SAR,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Compare the SAR radar backscatter intensities between May and August 2023.",
        ),
    },
    {
        "query": "Determine the growth in informal settlements in Mumbai between 2018 and 2023.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Mumbai",
            date_or_time_reference="between 2018 and 2023",
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Determine the growth in informal settlements in Mumbai between 2018 and 2023.",
        ),
    },
    {
        "query": "Has the wetland extent of Loktak Lake shrunk over the past 5 years?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Loktak Lake",
            date_or_time_reference="over the past 5 years",
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Has the wetland extent of Loktak Lake shrunk over the past 5 years?",
        ),
    },
    {
        "query": "Compare the burn scar progression in Uttarakhand between May 2023 and June 2023.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Uttarakhand",
            date_or_time_reference="between May 2023 and June 2023",
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Compare the burn scar progression in Uttarakhand between May 2023 and June 2023.",
        ),
    },
    {
        "query": "How much new residential construction appeared in Jaipur between 2022 and 2024?",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Jaipur",
            date_or_time_reference="between 2022 and 2024",
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="How much new residential construction appeared in Jaipur between 2022 and 2024?",
        ),
    },
    {
        "query": "Assess changes in soil moisture patterns before and after the monsoon.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location=None,
            date_or_time_reference="before and after the monsoon",
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.90,
            source=Source.LLM,
            raw_query="Assess changes in soil moisture patterns before and after the monsoon.",
        ),
    },
    {
        "query": "Track runway expansion at Delhi airport between 2020 and 2023.",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location="Delhi",
            date_or_time_reference="between 2020 and 2023",
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Track runway expansion at Delhi airport between 2020 and 2023.",
        ),
    },

    # =========================================================================
    # 5. Single-Task: Fusion Analysis (Optical + SAR / Radar) [15 queries]
    # =========================================================================
    {
        "query": "Combine optical and SAR imagery to identify flooded areas in Assam during cloud cover.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Assam",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.BOTH,
            confidence=0.96,
            source=Source.LLM,
            raw_query="Combine optical and SAR imagery to identify flooded areas in Assam during cloud cover.",
        ),
    },
    {
        "query": "Fuse optical and radar data to map urban building footprints in Mumbai.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Mumbai",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.BOTH,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Fuse optical and radar data to map urban building footprints in Mumbai.",
        ),
    },
    {
        "query": "Perform fusion analysis using Sentinel-2 optical and Sentinel-1 SAR for crop classification in Punjab.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Punjab",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.BOTH,
            confidence=0.96,
            source=Source.LLM,
            raw_query="Perform fusion analysis using Sentinel-2 optical and Sentinel-1 SAR for crop classification in Punjab.",
        ),
    },
    {
        "query": "Jointly analyze optical imagery together with SAR backscatter to detect ships near Chennai port.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Chennai",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.BOTH,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Jointly analyze optical imagery together with SAR backscatter to detect ships near Chennai port.",
        ),
    },
    {
        "query": "Use both optical and SAR modalities to measure forest canopy and biomass in Sundarbans.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Sundarbans",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.FOREST,
            sensor=Sensor.BOTH,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Use both optical and SAR modalities to measure forest canopy and biomass in Sundarbans.",
        ),
    },
    {
        "query": "Complement optical imagery with SAR data to evaluate cyclone damage in Odisha.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Odisha",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.BOTH,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Complement optical imagery with SAR data to evaluate cyclone damage in Odisha.",
        ),
    },
    {
        "query": "Fuse multispectral bands and radar backscatter for wetland boundary extraction in Kerala.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Kerala",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.BOTH,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Fuse multispectral bands and radar backscatter for wetland boundary extraction in Kerala.",
        ),
    },
    {
        "query": "Analyze this scene using multimodal optical and SAR sensors to delineate industrial infrastructure.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.BOTH,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Analyze this scene using multimodal optical and SAR sensors to delineate industrial infrastructure.",
        ),
    },
    {
        "query": "Perform cross-sensor fusion to assess agricultural soil moisture in Haryana.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Haryana",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.BOTH,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Perform cross-sensor fusion to assess agricultural soil moisture in Haryana.",
        ),
    },
    {
        "query": "Combine RISAT radar data and Cartosat optical imagery to inspect road networks in Himachal Pradesh.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Himachal Pradesh",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.BOTH,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Combine RISAT radar data and Cartosat optical imagery to inspect road networks in Himachal Pradesh.",
        ),
    },
    {
        "query": "Fuse optical and SAR to map landslide debris beneath cloud cover in Uttarakhand.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Uttarakhand",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.BOTH,
            confidence=0.96,
            source=Source.LLM,
            raw_query="Fuse optical and SAR to map landslide debris beneath cloud cover in Uttarakhand.",
        ),
    },
    {
        "query": "Integrate optical and radar layers for coastal water body delineation in Gujarat.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Gujarat",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.WATER,
            sensor=Sensor.BOTH,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Integrate optical and radar layers for coastal water body delineation in Gujarat.",
        ),
    },
    {
        "query": "Run a fusion analysis on both optical and SAR channels for this uploaded dataset.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.BOTH,
            confidence=0.92,
            source=Source.LLM,
            raw_query="Run a fusion analysis on both optical and SAR channels for this uploaded dataset.",
        ),
    },
    {
        "query": "Fuse multi-temporal SAR and optical sensors to classify urban building types in Delhi.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Delhi",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.BOTH,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Fuse multi-temporal SAR and optical sensors to classify urban building types in Delhi.",
        ),
    },
    {
        "query": "Combine NISAR radar and Landsat optical bands for rice paddy monitoring in Andhra Pradesh.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS],
            location="Andhra Pradesh",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.AGRICULTURE,
            sensor=Sensor.BOTH,
            confidence=0.96,
            source=Source.LLM,
            raw_query="Combine NISAR radar and Landsat optical bands for rice paddy monitoring in Andhra Pradesh.",
        ),
    },

    # =========================================================================
    # 6. Chained Multi-Task Queries [12 queries]
    # =========================================================================
    {
        "query": "Highlight the water body and tell me if it changed before and after monsoon.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.CHANGE_VQA],
            location=None,
            date_or_time_reference="before and after monsoon",
            target_object="the water body",
            domain=Domain.WATER,
            sensor=Sensor.OPTICAL,
            confidence=0.88,
            source=Source.LLM,
            raw_query="Highlight the water body and tell me if it changed before and after monsoon.",
        ),
    },
    {
        "query": "Locate the agricultural fields in Punjab and compare crop health 2022 vs 2024.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.CHANGE_VQA],
            location="Punjab",
            date_or_time_reference="2022 vs 2024",
            target_object="the agricultural fields",
            domain=Domain.AGRICULTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.92,
            source=Source.LLM,
            raw_query="Locate the agricultural fields in Punjab and compare crop health 2022 vs 2024.",
        ),
    },
    {
        "query": "Pinpoint the flooded zones in Patna and describe the damage extent.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.CAPTIONING],
            location="Patna",
            date_or_time_reference=None,
            target_object="the flooded zones",
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Pinpoint the flooded zones in Patna and describe the damage extent.",
        ),
    },
    {
        "query": "Highlight the built-up area in Bengaluru and assess how much it grew since 2020.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.CHANGE_VQA],
            location="Bengaluru",
            date_or_time_reference="2020",
            target_object="the built-up area",
            domain=Domain.URBAN,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Highlight the built-up area in Bengaluru and assess how much it grew since 2020.",
        ),
    },
    {
        "query": "Locate all cargo ships near Visakhapatnam port and give a description of maritime traffic.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.CAPTIONING],
            location="Visakhapatnam",
            date_or_time_reference=None,
            target_object="the ships",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.91,
            source=Source.LLM,
            raw_query="Locate all cargo ships near Visakhapatnam port and give a description of maritime traffic.",
        ),
    },
    {
        "query": "Fuse optical and SAR images of Assam and detect temporal flood changes.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS, Task.CHANGE_VQA],
            location="Assam",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.BOTH,
            confidence=0.95,
            source=Source.LLM,
            raw_query="Fuse optical and SAR images of Assam and detect temporal flood changes.",
        ),
    },
    {
        "query": "Highlight the deforestation patches in Sundarbans and count how many separate clusters exist.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.VQA],
            location="Sundarbans",
            date_or_time_reference=None,
            target_object="the deforestation patches",
            domain=Domain.FOREST,
            sensor=Sensor.OPTICAL,
            confidence=0.92,
            source=Source.LLM,
            raw_query="Highlight the deforestation patches in Sundarbans and count how many separate clusters exist.",
        ),
    },
    {
        "query": "Outline the airport runways in Delhi and verify if new terminals were added between 2021 and 2024.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.CHANGE_VQA],
            location="Delhi",
            date_or_time_reference="between 2021 and 2024",
            target_object="the runways",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Outline the airport runways in Delhi and verify if new terminals were added between 2021 and 2024.",
        ),
    },
    {
        "query": "Combine optical and radar data for Mumbai and locate all oil storage tanks.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS, Task.GROUNDING],
            location="Mumbai",
            date_or_time_reference=None,
            target_object="the oil tanks",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.BOTH,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Combine optical and radar data for Mumbai and locate all oil storage tanks.",
        ),
    },
    {
        "query": "Locate the landslide scar in Wayanad Kerala and describe the debris path.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.CAPTIONING],
            location="Wayanad",
            date_or_time_reference=None,
            target_object="the landslide debris",
            domain=Domain.DISASTER,
            sensor=Sensor.OPTICAL,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Locate the landslide scar in Wayanad Kerala and describe the debris path.",
        ),
    },
    {
        "query": "Highlight solar farms in Rajasthan and check if new panels were installed over the past 2 years.",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING, Task.CHANGE_VQA],
            location="Rajasthan",
            date_or_time_reference="over the past 2 years",
            target_object="the solar panels",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.OPTICAL,
            confidence=0.93,
            source=Source.LLM,
            raw_query="Highlight solar farms in Rajasthan and check if new panels were installed over the past 2 years.",
        ),
    },
    {
        "query": "Fuse SAR and optical data over Cuttack and assess the number of flooded bridges.",
        "expected": InterpretedQuery(
            task_sequence=[Task.FUSION_ANALYSIS, Task.VQA],
            location="Cuttack",
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.BOTH,
            confidence=0.94,
            source=Source.LLM,
            raw_query="Fuse SAR and optical data over Cuttack and assess the number of flooded bridges.",
        ),
    },

    # =========================================================================
    # 7. Ambiguous, Casual, and Minimal Signal Queries [10 queries]
    # =========================================================================
    {
        "query": "tell me about this",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.UNSPECIFIED,
            confidence=0.30,
            source=Source.LLM,
            raw_query="tell me about this",
        ),
    },
    {
        "query": "what is this",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.UNSPECIFIED,
            confidence=0.30,
            source=Source.LLM,
            raw_query="what is this",
        ),
    },
    {
        "query": "compare",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.UNSPECIFIED,
            confidence=0.35,
            source=Source.LLM,
            raw_query="compare",
        ),
    },
    {
        "query": "look at the changes here",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.UNSPECIFIED,
            confidence=0.40,
            source=Source.LLM,
            raw_query="look at the changes here",
        ),
    },
    {
        "query": "show me the water",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location=None,
            date_or_time_reference=None,
            target_object="the water body",
            domain=Domain.WATER,
            sensor=Sensor.UNSPECIFIED,
            confidence=0.45,
            source=Source.LLM,
            raw_query="show me the water",
        ),
    },
    {
        "query": "SAR ship detection Kochi",
        "expected": InterpretedQuery(
            task_sequence=[Task.GROUNDING],
            location="Kochi",
            date_or_time_reference=None,
            target_object="the ships",
            domain=Domain.INFRASTRUCTURE,
            sensor=Sensor.SAR,
            confidence=0.85,
            source=Source.LLM,
            raw_query="SAR ship detection Kochi",
        ),
    },
    {
        "query": "urban expansion rate",
        "expected": InterpretedQuery(
            task_sequence=[Task.CHANGE_VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.URBAN,
            sensor=Sensor.UNSPECIFIED,
            confidence=0.45,
            source=Source.LLM,
            raw_query="urban expansion rate",
        ),
    },
    {
        "query": "overview of the scene",
        "expected": InterpretedQuery(
            task_sequence=[Task.CAPTIONING],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.UNSPECIFIED,
            confidence=0.45,
            source=Source.LLM,
            raw_query="overview of the scene",
        ),
    },
    {
        "query": "process this radar image",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.GENERAL,
            sensor=Sensor.SAR,
            confidence=0.40,
            source=Source.LLM,
            raw_query="process this radar image",
        ),
    },
    {
        "query": "is there flooding",
        "expected": InterpretedQuery(
            task_sequence=[Task.VQA],
            location=None,
            date_or_time_reference=None,
            target_object=None,
            domain=Domain.DISASTER,
            sensor=Sensor.UNSPECIFIED,
            confidence=0.50,
            source=Source.LLM,
            raw_query="is there flooding",
        ),
    },
]


def get_query_bank() -> List[Dict[str, Any]]:
    """Returns the full list of query bank records."""
    return QUERY_BANK


def get_queries_by_task(task: Task) -> List[Dict[str, Any]]:
    """Filters query bank entries containing the specified task."""
    return [entry for entry in QUERY_BANK if task in entry["expected"].task_sequence]


def get_queries_by_domain(domain: Domain) -> List[Dict[str, Any]]:
    """Filters query bank entries by domain category."""
    return [entry for entry in QUERY_BANK if entry["expected"].domain == domain]


def get_chained_queries() -> List[Dict[str, Any]]:
    """Returns all multi-task chained queries (task_sequence length > 1)."""
    return [entry for entry in QUERY_BANK if len(entry["expected"].task_sequence) > 1]


def get_upload_only_queries() -> List[Dict[str, Any]]:
    """Returns all queries without explicit geographical locations."""
    return [entry for entry in QUERY_BANK if entry["expected"].location is None]


# ---------------------------------------------------------------------------
# Extension: +63 queries targeting real benchmarked failure patterns
# (domain disambiguation, yes/no-vs-grounding, captioning-vs-vqa).
# Brings the bank from 137 to 200 total.
# ---------------------------------------------------------------------------
try:
    from .query_bank_extension import EXTENSION_QUERIES
except ImportError:
    from query_bank_extension import EXTENSION_QUERIES

QUERY_BANK.extend(EXTENSION_QUERIES)
try:
    from .query_bank_extension_2 import GAP_FILL_QUERIES
except ImportError:
    from query_bank_extension_2 import GAP_FILL_QUERIES

QUERY_BANK.extend(GAP_FILL_QUERIES)
